---
functional:
  # Вёрстка
  - Сайт должен иметь мобильную версию.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  # Каталог и карточки товара
  - Пользователь может просматривать каталог товаров фильтруя их и пользуясь постраничным выводом без перезагрузки страницы.
  - На странице товара и в каталоге выводятся название, рейтинг, цена со скидкой и без.
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру и т.д.
  # Корзина
  - Пользователь должен иметь возможность добавлять товары в корзину.
  - Пользователь должен иметь возможность просматривать содержимое корзины.
  - После добавления товара в корзину пользователь должен иметь возможность продолжить просмотр каталога.
  - На странице корзины пользователь может удалить товар из корзины.
  - На странице корзины пользователь может оформить заказ с переходом на страницу оплаты.
  - Корзина хранится в сессии браузера.
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Веб-сайт должен быть разработан с учетом удобства использования.
  - Сайт должен быть способен обрабатывать большое количество трафика.
implicit:
  - Цены должны быть указаны в рублях